for current service template,  some empty service needs to be present in base values.yaml. Otehrwise, we get these errors:
Error: UPGRADE FAILED: template: component-chart/templates/serviceaccount.yaml:1:14: executing "component-chart/templates/serviceaccount.yaml" at <.Values.customServiceAccount.create>: nil pointer evaluating interface {}.create